apiVersion: v1
kind: Service
metadata:
  name: apisix-etcd
  namespace: k8s-api-gateway
spec:
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  selector:
    app: apisix-etcd
