apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  name: opentelemetry-global
  namespace: k8s-api-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  plugins:
    - name: opentelemetry
      enable: true
      config:
        sampler:
          name: always_on
        collector:
          address: otel-collector.observability.svc.cluster.local:4318
        resource:
          service.name: apisix-gateway-internal
          service.namespace: k8s-api-gateway
