apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  name: opentelemetry-global
  namespace: k8s-api-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  plugins:
    - name: opentelemetry
      enable: true
      config:
        sampler:
          name: always_on
        collector:
          address: otel-collector.observability.svc.cluster.local:4318
        resource:
          service.name: gravitee-gateway
          service.namespace: k8s-api-gateway
---
apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  name: real-ip-global
  namespace: k8s-api-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  plugins:
    - name: real-ip
      enable: true
      config:
        source: X-Forwarded-For
        recursive: true
        trusted_addresses:
          - 127.0.0.1
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
